# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20140524091109) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "details", force: true do |t|
    t.string   "detail_desc"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "events", force: true do |t|
    t.string   "event_desc"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "games", primary_key: "game_id", force: true do |t|
    t.date     "date"
    t.integer  "year"
    t.integer  "home_team_id"
    t.integer  "away_team_id"
    t.string   "venue_name"
    t.string   "venue_city"
    t.string   "venue_state"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "games", ["away_team_id"], name: "index_games_on_away_team_id", using: :btree
  add_index "games", ["home_team_id"], name: "index_games_on_home_team_id", using: :btree

  create_table "player_basic_stats", primary_key: "player_id", force: true do |t|
    t.integer  "team_id"
    t.integer  "games_played"
    t.integer  "sum_field_goals_att"
    t.float    "points_per_game"
    t.float    "rebounds_per_game"
    t.float    "assists_per_game"
    t.float    "steals_per_game"
    t.float    "blocks_per_game"
    t.float    "turnovers_per_game"
    t.float    "minutes_per_game"
    t.float    "field_goals_pct"
    t.float    "free_throws_pct"
    t.float    "three_point_field_goals_pct"
    t.float    "effective_field_goals_pct"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "player_games", force: true do |t|
    t.integer  "player_id"
    t.integer  "game_id"
    t.integer  "team_id"
    t.string   "player_first_name"
    t.string   "player_last_name"
    t.integer  "player_position"
    t.integer  "player_uniform_number"
    t.integer  "field_goals_made"
    t.integer  "field_goals_att"
    t.float    "field_goals_pct"
    t.integer  "free_throws_made"
    t.integer  "free_throws_att"
    t.float    "free_throws_pct"
    t.integer  "three_point_field_goals_made"
    t.integer  "three_point_field_goals_att"
    t.float    "three_point_field_goals_pct"
    t.integer  "points"
    t.integer  "rebounds_total"
    t.integer  "rebounds_off"
    t.integer  "rebounds_def"
    t.integer  "assists"
    t.integer  "steals"
    t.integer  "blocked_shots"
    t.integer  "turnovers"
    t.integer  "personal_fouls"
    t.integer  "disqualifications"
    t.integer  "technical_fouls"
    t.integer  "minutes"
    t.boolean  "starter"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "player_games", ["game_id"], name: "index_player_games_on_game_id", using: :btree
  add_index "player_games", ["player_id"], name: "index_player_games_on_player_id", using: :btree
  add_index "player_games", ["team_id"], name: "index_player_games_on_team_id", using: :btree

  create_table "player_shot_stats", primary_key: "player_id", force: true do |t|
    t.integer  "team_id"
    t.integer  "shots_att"
    t.integer  "shots_made"
    t.float    "shots_pct"
    t.integer  "right_corner_3_att"
    t.integer  "right_corner_3_made"
    t.float    "right_corner_3_pct_att"
    t.float    "right_corner_3_pct_made"
    t.integer  "right_wing_3_att"
    t.integer  "right_wing_3_made"
    t.float    "right_wing_3_pct_att"
    t.float    "right_wing_3_pct_made"
    t.integer  "straight_up_3_att"
    t.integer  "straight_up_3_made"
    t.float    "straight_up_3_pct_att"
    t.float    "straight_up_3_pct_made"
    t.integer  "left_wing_3_att"
    t.integer  "left_wing_3_made"
    t.float    "left_wing_3_pct_att"
    t.float    "left_wing_3_pct_made"
    t.integer  "left_corner_3_att"
    t.integer  "left_corner_3_made"
    t.float    "left_corner_3_pct_att"
    t.float    "left_corner_3_pct_made"
    t.integer  "right_baseline_2_att"
    t.integer  "right_baseline_2_made"
    t.float    "right_baseline_2_pct_att"
    t.float    "right_baseline_2_pct_made"
    t.integer  "right_wing_2_att"
    t.integer  "right_wing_2_made"
    t.float    "right_wing_2_pct_att"
    t.float    "right_wing_2_pct_made"
    t.integer  "straight_up_2_att"
    t.integer  "straight_up_2_made"
    t.float    "straight_up_2_pct_att"
    t.float    "straight_up_2_pct_made"
    t.integer  "left_wing_2_att"
    t.integer  "left_wing_2_made"
    t.float    "left_wing_2_pct_att"
    t.float    "left_wing_2_pct_made"
    t.integer  "left_baseline_2_att"
    t.integer  "left_baseline_2_made"
    t.float    "left_baseline_2_pct_att"
    t.float    "left_baseline_2_pct_made"
    t.integer  "right_high_paint_att"
    t.integer  "right_high_paint_made"
    t.float    "right_high_paint_pct_att"
    t.float    "right_high_paint_pct_made"
    t.integer  "left_high_paint_att"
    t.integer  "left_high_paint_made"
    t.float    "left_high_paint_pct_att"
    t.float    "left_high_paint_pct_made"
    t.integer  "right_low_paint_att"
    t.integer  "right_low_paint_made"
    t.float    "right_low_paint_pct_att"
    t.float    "right_low_paint_pct_made"
    t.integer  "left_low_paint_att"
    t.integer  "left_low_paint_made"
    t.float    "left_low_paint_pct_att"
    t.float    "left_low_paint_pct_made"
    t.integer  "at_rim_att"
    t.integer  "at_rim_made"
    t.float    "at_rim_pct_att"
    t.float    "at_rim_pct_made"
    t.integer  "corner_3_att"
    t.integer  "corner_3_made"
    t.float    "corner_3_pct_att"
    t.float    "corner_3_pct_made"
    t.integer  "wing_3_att"
    t.integer  "wing_3_made"
    t.float    "wing_3_pct_att"
    t.float    "wing_3_pct_made"
    t.integer  "baseline_2_att"
    t.integer  "baseline_2_made"
    t.float    "baseline_2_pct_att"
    t.float    "baseline_2_pct_made"
    t.integer  "wing_2_att"
    t.integer  "wing_2_made"
    t.float    "wing_2_pct_att"
    t.float    "wing_2_pct_made"
    t.integer  "high_paint_att"
    t.integer  "high_paint_made"
    t.float    "high_paint_pct_att"
    t.float    "high_paint_pct_made"
    t.integer  "low_paint_att"
    t.integer  "low_paint_made"
    t.float    "low_paint_pct_att"
    t.float    "low_paint_pct_made"
    t.integer  "threes_att"
    t.integer  "threes_made"
    t.float    "threes_pct_att"
    t.float    "threes_pct_made"
    t.integer  "outside_the_paint_att"
    t.integer  "outside_the_paint_made"
    t.float    "outside_the_paint_pct_att"
    t.float    "outside_the_paint_pct_made"
    t.integer  "in_the_paint_att"
    t.integer  "in_the_paint_made"
    t.float    "in_the_paint_pct_att"
    t.float    "in_the_paint_pct_made"
    t.integer  "short_att"
    t.integer  "short_made"
    t.float    "short_pct_att"
    t.float    "short_pct_made"
    t.integer  "mid_att"
    t.integer  "mid_made"
    t.float    "mid_pct_att"
    t.float    "mid_pct_made"
    t.integer  "long_att"
    t.integer  "long_made"
    t.float    "long_pct_att"
    t.float    "long_pct_made"
    t.integer  "jump_shots_att"
    t.integer  "jump_shots_made"
    t.float    "jump_shots_pct_att"
    t.float    "jump_shots_pct_made"
    t.integer  "hook_shots_att"
    t.integer  "hook_shots_made"
    t.float    "hook_shots_pct_att"
    t.float    "hook_shots_pct_made"
    t.integer  "tip_shots_att"
    t.integer  "tip_shots_made"
    t.float    "tip_shots_pct_att"
    t.float    "tip_shots_pct_made"
    t.integer  "layup_shots_att"
    t.integer  "layup_shots_made"
    t.float    "layup_shots_pct_att"
    t.float    "layup_shots_pct_made"
    t.integer  "dunk_shots_att"
    t.integer  "dunk_shots_made"
    t.float    "dunk_shots_pct_att"
    t.float    "dunk_shots_pct_made"
    t.integer  "at_rim_layup_shots_att"
    t.integer  "at_rim_layup_shots_made"
    t.float    "at_rim_layup_shots_pct_att"
    t.float    "at_rim_layup_shots_pct_made"
    t.integer  "at_rim_dunk_shots_att"
    t.integer  "at_rim_dunk_shots_made"
    t.float    "at_rim_dunk_shots_pct_att"
    t.float    "at_rim_dunk_shots_pct_made"
    t.float    "layup_shots_per_at_rim_shots_pct_att"
    t.float    "dunk_shots_per_at_rim_shots_pct_att"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "players", primary_key: "player_id", force: true do |t|
    t.integer  "team_id"
    t.string   "player_first_name"
    t.string   "player_last_name"
    t.integer  "player_position"
    t.integer  "player_uniform_number"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "players", ["team_id"], name: "index_players_on_team_id", using: :btree

  create_table "plays", force: true do |t|
    t.integer  "game_id"
    t.integer  "half"
    t.integer  "time_minutes"
    t.integer  "time_seconds"
    t.string   "details"
    t.integer  "player_id_1"
    t.integer  "player_id_2"
    t.string   "player_first_name_1"
    t.string   "player_first_name_2"
    t.string   "player_last_name_1"
    t.string   "player_last_name_2"
    t.integer  "home_score"
    t.integer  "visitor_score"
    t.integer  "visitor_fouls"
    t.integer  "home_fouls"
    t.integer  "player_score"
    t.integer  "points_type"
    t.string   "detail_desc"
    t.string   "event_desc"
    t.integer  "distance"
    t.float    "x_coord"
    t.float    "y_coord"
    t.integer  "team_id_1"
    t.integer  "team_id_2"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "plays", ["game_id"], name: "index_plays_on_game_id", using: :btree
  add_index "plays", ["player_id_1"], name: "index_plays_on_player_id_1", using: :btree
  add_index "plays", ["team_id_1"], name: "index_plays_on_team_id_1", using: :btree

  create_table "shots", force: true do |t|
    t.integer  "play_id"
    t.integer  "player_id"
    t.integer  "team_id"
    t.integer  "game_id"
    t.integer  "half"
    t.string   "details"
    t.integer  "points_type"
    t.integer  "distance"
    t.float    "x_coord"
    t.float    "y_coord"
    t.integer  "detail_id"
    t.integer  "zone_id"
    t.boolean  "made"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "shots", ["detail_id"], name: "index_shots_on_detail_id", using: :btree
  add_index "shots", ["game_id"], name: "index_shots_on_game_id", using: :btree
  add_index "shots", ["play_id"], name: "index_shots_on_play_id", using: :btree
  add_index "shots", ["player_id"], name: "index_shots_on_player_id", using: :btree
  add_index "shots", ["team_id"], name: "index_shots_on_team_id", using: :btree
  add_index "shots", ["zone_id"], name: "index_shots_on_zone_id", using: :btree

  create_table "team_games", force: true do |t|
    t.integer  "game_id"
    t.integer  "team_id"
    t.integer  "field_goals_made"
    t.integer  "field_goals_att"
    t.float    "field_goals_pct"
    t.integer  "free_throws_made"
    t.integer  "free_throws_att"
    t.float    "free_throws_pct"
    t.integer  "three_point_field_goals_made"
    t.integer  "three_point_field_goals_att"
    t.float    "three_point_field_goals_pct"
    t.integer  "points"
    t.integer  "rebounds_total"
    t.integer  "rebounds_off"
    t.integer  "rebounds_def"
    t.integer  "assists"
    t.integer  "steals"
    t.integer  "blocked_shots"
    t.integer  "turnovers"
    t.integer  "personal_fouls"
    t.integer  "technical_fouls"
    t.integer  "minutes"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "team_shot_stats", primary_key: "team_id", force: true do |t|
    t.integer  "shots_att"
    t.integer  "shots_made"
    t.float    "shots_pct"
    t.integer  "right_corner_3_att"
    t.integer  "right_corner_3_made"
    t.float    "right_corner_3_pct_att"
    t.float    "right_corner_3_pct_made"
    t.integer  "right_wing_3_att"
    t.integer  "right_wing_3_made"
    t.float    "right_wing_3_pct_att"
    t.float    "right_wing_3_pct_made"
    t.integer  "straight_up_3_att"
    t.integer  "straight_up_3_made"
    t.float    "straight_up_3_pct_att"
    t.float    "straight_up_3_pct_made"
    t.integer  "left_wing_3_att"
    t.integer  "left_wing_3_made"
    t.float    "left_wing_3_pct_att"
    t.float    "left_wing_3_pct_made"
    t.integer  "left_corner_3_att"
    t.integer  "left_corner_3_made"
    t.float    "left_corner_3_pct_att"
    t.float    "left_corner_3_pct_made"
    t.integer  "right_baseline_2_att"
    t.integer  "right_baseline_2_made"
    t.float    "right_baseline_2_pct_att"
    t.float    "right_baseline_2_pct_made"
    t.integer  "right_wing_2_att"
    t.integer  "right_wing_2_made"
    t.float    "right_wing_2_pct_att"
    t.float    "right_wing_2_pct_made"
    t.integer  "straight_up_2_att"
    t.integer  "straight_up_2_made"
    t.float    "straight_up_2_pct_att"
    t.float    "straight_up_2_pct_made"
    t.integer  "left_wing_2_att"
    t.integer  "left_wing_2_made"
    t.float    "left_wing_2_pct_att"
    t.float    "left_wing_2_pct_made"
    t.integer  "left_baseline_2_att"
    t.integer  "left_baseline_2_made"
    t.float    "left_baseline_2_pct_att"
    t.float    "left_baseline_2_pct_made"
    t.integer  "right_high_paint_att"
    t.integer  "right_high_paint_made"
    t.float    "right_high_paint_pct_att"
    t.float    "right_high_paint_pct_made"
    t.integer  "left_high_paint_att"
    t.integer  "left_high_paint_made"
    t.float    "left_high_paint_pct_att"
    t.float    "left_high_paint_pct_made"
    t.integer  "right_low_paint_att"
    t.integer  "right_low_paint_made"
    t.float    "right_low_paint_pct_att"
    t.float    "right_low_paint_pct_made"
    t.integer  "left_low_paint_att"
    t.integer  "left_low_paint_made"
    t.float    "left_low_paint_pct_att"
    t.float    "left_low_paint_pct_made"
    t.integer  "at_rim_att"
    t.integer  "at_rim_made"
    t.float    "at_rim_pct_att"
    t.float    "at_rim_pct_made"
    t.integer  "corner_3_att"
    t.integer  "corner_3_made"
    t.float    "corner_3_pct_att"
    t.float    "corner_3_pct_made"
    t.integer  "wing_3_att"
    t.integer  "wing_3_made"
    t.float    "wing_3_pct_att"
    t.float    "wing_3_pct_made"
    t.integer  "baseline_2_att"
    t.integer  "baseline_2_made"
    t.float    "baseline_2_pct_att"
    t.float    "baseline_2_pct_made"
    t.integer  "wing_2_att"
    t.integer  "wing_2_made"
    t.float    "wing_2_pct_att"
    t.float    "wing_2_pct_made"
    t.integer  "high_paint_att"
    t.integer  "high_paint_made"
    t.float    "high_paint_pct_att"
    t.float    "high_paint_pct_made"
    t.integer  "low_paint_att"
    t.integer  "low_paint_made"
    t.float    "low_paint_pct_att"
    t.float    "low_paint_pct_made"
    t.integer  "threes_att"
    t.integer  "threes_made"
    t.float    "threes_pct_att"
    t.float    "threes_pct_made"
    t.integer  "outside_the_paint_att"
    t.integer  "outside_the_paint_made"
    t.float    "outside_the_paint_pct_att"
    t.float    "outside_the_paint_pct_made"
    t.integer  "in_the_paint_att"
    t.integer  "in_the_paint_made"
    t.float    "in_the_paint_pct_att"
    t.float    "in_the_paint_pct_made"
    t.integer  "short_att"
    t.integer  "short_made"
    t.float    "short_pct_att"
    t.float    "short_pct_made"
    t.integer  "mid_att"
    t.integer  "mid_made"
    t.float    "mid_pct_att"
    t.float    "mid_pct_made"
    t.integer  "long_att"
    t.integer  "long_made"
    t.float    "long_pct_att"
    t.float    "long_pct_made"
    t.integer  "jump_shots_att"
    t.integer  "jump_shots_made"
    t.float    "jump_shots_pct_att"
    t.float    "jump_shots_pct_made"
    t.integer  "hook_shots_att"
    t.integer  "hook_shots_made"
    t.float    "hook_shots_pct_att"
    t.float    "hook_shots_pct_made"
    t.integer  "tip_shots_att"
    t.integer  "tip_shots_made"
    t.float    "tip_shots_pct_att"
    t.float    "tip_shots_pct_made"
    t.integer  "layup_shots_att"
    t.integer  "layup_shots_made"
    t.float    "layup_shots_pct_att"
    t.float    "layup_shots_pct_made"
    t.integer  "dunk_shots_att"
    t.integer  "dunk_shots_made"
    t.float    "dunk_shots_pct_att"
    t.float    "dunk_shots_pct_made"
    t.integer  "at_rim_layup_shots_att"
    t.integer  "at_rim_layup_shots_made"
    t.float    "at_rim_layup_shots_pct_att"
    t.float    "at_rim_layup_shots_pct_made"
    t.integer  "at_rim_dunk_shots_att"
    t.integer  "at_rim_dunk_shots_made"
    t.float    "at_rim_dunk_shots_pct_att"
    t.float    "at_rim_dunk_shots_pct_made"
    t.float    "layup_shots_per_at_rim_shots_pct_att"
    t.float    "dunk_shots_per_at_rim_shots_pct_att"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "teams", primary_key: "team_id", force: true do |t|
    t.string   "team_alias"
    t.string   "team_name"
    t.string   "team_mascot"
    t.string   "team_div"
    t.string   "team_conf"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "zones", force: true do |t|
    t.string   "zone_desc"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
